<?php

namespace Tests\Browser\Users;

use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use NeubusSrm\Models\Org\Project;
use NeubusSrm\Models\Auth\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;

/**
 * Class UserAdminDeleteTest
 * @package Tests\Browser\Users
 */
class UserAdminDeleteTest extends DuskTestCase
{
    use DatabaseMigrations;
    protected $user,$userLogin;

    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        $project = factory(Project::class)->create();
        $this->userLogin = factory(User::class)->create([
            'role' => User::ROLE_ADMIN,
            'company_id' => $project->company_id
        ]);
        $this->user = factory(User::class)->create();
    }







    public function testCanDeleteUser()
    {
        $this->markTestIncomplete('Needs further refactoring before viable');
        $project = factory(Project::class)->create();
        $user = $this->userLogin;


        $this->browse(function (Browser $browser) use ($user, $project) {
            $browser->loginAs($user)
                ->visit('/client/users')
                ->pause(5000)
                ->with('@neu-table', function ($table) {
                    $table  ->assertSee($this->userLogin->email)
                            ->click('@neu-delete-row');
                });
        });
    }

    public function testCanDeleteUserRemoveRow()
    {
        $this->markTestIncomplete('Needs further refactoring before viable');
        $project = factory(Project::class)->create();
        $user = $this->userLogin;


        $this->browse(function (Browser $browser) use ($user, $project) {
            $browser->loginAs($user)
                ->visit('/client/users')
                ->pause(5000)
                ->with('@neu-table', function ($table) {
                    $table  ->assertSee($this->userLogin->email)
                        ->click('@neu-delete-row');
                })
                ->press('OK')
                ->waitFor('@statusCRUD')
                ->assertSeeIn('@statusCRUD', "User deleted succesfully. ")
                ->with('@neu-table', function ($table) {
                    $table  ->assertDontSee($this->userLogin->email);
                });
        });
    }

}
